### ISSUE TITLE
Cannot filter only staged files

### ISSUE THREAD

**Issue by wKich** [mixu/fastlint#1]
`fastlint --status` outputs all files staged and not staged in one list.

**Comment by mikito-stripe** [comment]
Thanks for reporting! I just added this feature via `--staged` in `v.1.1.0` - see the readme.

**Comment by mixu** [comment]
Thanks for reporting! I just added this feature via --staged in v.1.1.0 - see the readme.

**Comment by wKich** [comment]
Thank you very much.
